### ISSUE TITLE
Incorrect syntax for enabling autoindex directive

### ISSUE THREAD

**Issue by butch-lextegrity** [davralin/nginx-autoindex#1]
I started to see this fatal error on startup from the container running nginx-autoindex:

`nginx: [emerg] unknown directive "auto_index" in /etc/nginx/conf.d/default.conf:4`

I believe the correct syntax is `autoindex`

**Comment by butch-lextegrity** [comment]
#2

**Comment by davralin** [comment]
Closed with #2
